name: chat_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  firebase_core:
  google_sign_in:
  shared_preferences:
  random_string:
  cloud_firestore:
  flutter_signin_button: ^1.1.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  shimmer: ^1.1.2
  url_launcher: ^6.0.2
  flutter_phoenix: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
